### ISSUE TITLE
Polish keyboard layout

### ISSUE THREAD

**Issue by Zjemm** [szatanszmatan/myrdp#3]
Hi,

I noticed when using myrdp to connect to several windows machines the keyboard layout is changed to Polish. This is strange because i'm not polish, and never use this language
when i login with remmina to these same windows machines, this does not happen.

i tried searching the myrdp files for references to polish laguage, but could not find any.
so i'm not sure if this is a myrdp thing at all

any thoughts on this?

**Comment by szatanszmatan** [comment]
Hi,
in conf/config.yaml from line xfreerdp -> args (8 line) please remove argument "/kbd:0x00000415", this sets polish keyboard layout :)

**Comment by szatanszmatan** [comment]
In commit 84e2fdeeca93871582f200b54e27e6adee320085, I have removed polish keyboard layout from settings ;)

Thank you for report ;)
