### ISSUE TITLE
passwords not saved securely

### ISSUE THREAD

**Issue by Zjemm** [szatanszmatan/myrdp#4]
Hi,

still using your software :)

i noticed that the hosts and usernames and passwords are saved in a sqlite db file. but this db has no security at all. so when opening the db file, everybody can read the saved usernames and passwords.

i'm not sure if you are still working on this project, but i thought i inform you about this.

at least the passwords should be saved securely

**Comment by szatanszmatan** [comment]
Hello,
Thanks for creating issue ;) Passwords in database are now encrypted with private key located in `~/.config/myrdp/private.key`. There is also possibility to set passphrase for this key (settings -> set master password). If passphrase is set, then will be required on application start.

Best Regards,
mj

**Comment by Zjemm** [comment]
Nice work, I'll look into it


Op 26 feb. 2018 21:25 schreef szatanszmatan <notifications@github.com>:

Hello,
Thanks for creating issue ;) Passwords in database are now encrypted with private key located in ~/.config/myrdp/private.key. There is also possibility to set passphrase for this key (settings -> set master password). If passphrase is set, then will be required on application start.

Best Regards,
mj
